### PR TITLE
Updated method method in JqueryCaller.php

### PR DESCRIPTION
**Pull request by webdevilopers**
Added usage for callback functions fixes issue #4 .
Baesd on `ZfcDatagrid` code https://github.com/ThaDafinser/ZfcDatagrid/blob/master/src/ZfcDatagrid/Renderer/JqGrid/View/Helper/Columns.php#L150-L153 .

### CODE REVIEW

**Comment by webdevilopers** [comment]
Example usage:

``` php
$this->add(array(
    'name' => 'autocomplete',
    'type' => 'Autocomplete',
    'attributes' => array(
        'jquery' => array(
            'source' => 'data-source.php',
            'select' => 'function( event, ui ) { $( this ).val( ui.item.label ); return false; }'
        ),
    )
));
```

**Comment by webdevilopers** [comment]
Please note that this will not enable you to add a callback via function var / name e.g.:

``` php
$this->add(array(
    'name' => 'autocomplete',
    'type' => 'Autocomplete',
    'attributes' => array(
        'jquery' => array(
            'source' => 'data-source.php',
            'select' => 'mySelectFunction'
        ),
    )
));
```

``` javascript
var mySelectFunction = function( event, ui ) { $( this ).val( ui.item.label ); return false; }
```

A possible solution to this could be passing a function var / name in a `json` format to make the `method()` method recognize it and pass it without quotes. But this still has to be discussed.

**Comment by webdevilopers** [comment]
BTW: This generally adds callback usage to every jquery form element.

If it was only the `Autocompleter` we would have had to create an individual `JqueryCaller()` via `buildCaller()` method  inside the `render()` method inside the `Autocomplete` view helper.

**Comment by webdevilopers** [comment]
Any thoughts on escaping the content of the users function?

**Comment by snapshotpl** [comment]
Hi @webdevilopers ! Thank's for PR! Have you tried to use Zend\Json\Expr (http://framework.zend.com/manual/2.3/en/modules/zend.json.objects.html)?

**Comment by webdevilopers** [comment]
I will try it and get back to you shortly, @snapshotpl ! BTW: Did you get my email and FB PM?

**Comment by webdevilopers** [comment]
I commited the change, @snapshotpl ! If the passed jquery attribute is a function it will now be properly escaped creating a Json/Expr for it.
This makes it work perfetctely with your `jsonEncode()` method since you added the `enableJsonExprFinder` option set to `true`.

Please have a look at the added `foreach` block:

``` php
        foreach ($params as $param) {
            foreach ($param as $key => $value) {
                if (stripos($value, 'function') === 0) {
                    $value = new Expr($value);
                }
                $methodParam = (string) $key . ': ' . $this->jsonEncode($value);
                $methodParams[] = $methodParam;
            }
        }
```

Is there a better practice for PHP to prevent using this `foreach` by using some kind of callback on the `params` parent array?

**Comment by webdevilopers** [comment]
I just recognized that this will break the usage for `source` as an Array:
http://api.jqueryui.com/autocomplete/#option-source

>    An array of objects with label and value properties: [ { label: "Choice1", value: "value1" }, ... ]
> The label property is displayed in the suggestion menu. The value will be inserted into the input element when a user selects an item. If just one property is specified, it will be used for both, e.g., if you provide only value properties, the value will also be used as the label. 

I will add this feature to the PR, @snapshotpl .

**Comment by webdevilopers** [comment]
Correcting myself the method will work for this use case. Example code:

``` php
$this->add(array(
    'name' => 'autocomplete',
    'type' => 'Autocomplete',
    'attributes' => array(
        'jquery' => array(
            'source' => array(
                array('label' => 'foo', 'value' => '1'),
                array('label' => 'bar', 'value' => '2'),
                array('label' => 'baz', 'value' => '3')
            )
        ),
    ),
));
```

I only had to add a `!is_array($value)` check to prevent `stripos` from firing an error.

**Comment by webdevilopers** [comment]
If this PR is merged I could update the docs for several use cases, @snapshotpl .

**Comment by webdevilopers** [comment]
@snapshotpl Have you received my messages on Facebook ? Can I contact you somewhere else , Twitter, Email ?

**Comment by webdevilopers** [comment]
Any comments on this @snapshotpl ? This would really help using several jquery use cases.

**Comment by snapshotpl** [comment]
Try:

``` php
$this->add(array(
    'name' => 'autocomplete',
    'type' => 'Autocomplete',
    'attributes' => array(
        'jquery' => array(
            'source' => 'data-source.php',
            'select' => new \Zend\Json\Expr('function( event, ui ) { $( this ).val( ui.item.label ); return false; }'),
        ),
    )
));
```

**Comment by webdevilopers** [comment]
Finally @snapshotpl  I understand what you were trying to tell me in the first place.
I will close this PR.

I will open up a new issue to improve the docs for these use cases and create a PR for that so others don't run into the same trap, ok ?

**Comment by snapshotpl** [comment]
Good idea @webdevilopers

**Pull request closed without merging**
